apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-content
  namespace: sample-apps
  labels:
    app: sample-web-app
data:
  # To update the web app:
  # 1. Edit the HTML content below directly
  # 2. Apply: kubectl apply -f configmap.yaml
  # 3. Restart: kubectl rollout restart deployment/sample-web-app -n sample-apps
  
  index.html: |
    <!DOCTYPE html>

    <html>

    <body>

        <h1>This K8s CICD pipeline DEMO</h1>

        <p>Running on Kubernetes</p>

    </body>

    </html>

    

